# Generated by Django 4.1.2 on 2022-10-24 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='collage',
            field=models.CharField(choices=[('هندسة معلوماتية', 'هندسة معلوماتية'), ('هندسة إتصالات', 'هندسة إتصالات'), ('طب بشري', 'طب بشري'), ('طب أسنان', 'طب أسنان'), ('هندسة معمارية', 'هندسة معمارية'), ('هندسة كهرباء', 'هندسة كهرباء'), ('هندسة طبية', 'هندسة طبية'), ('هندسة حاسبات', 'هندسة حاسبات')], default='هندسة معلوماتية', max_length=100),
        ),
    ]
