# Generated by Django 4.1.2 on 2022-10-24 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_collage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='status',
            field=models.CharField(choices=[('student', 'student'), ('proffisor', 'proffisor'), ('employee', 'employee')], default='student', max_length=100),
        ),
    ]
