# Generated by Django 4.1.2 on 2022-10-22 13:14

import builtins
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('year', models.IntegerField(max_length=2)),
                ('prof', models.ForeignKey(on_delete=builtins.callable, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
