# Generated by Django 4.1.2 on 2022-10-22 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_subject_prof'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='year',
            field=models.IntegerField(),
        ),
    ]
