# Generated by Django 4.1.2 on 2022-10-25 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_subject_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='image',
            field=models.ImageField(blank=True, default='images/default/group.png', null=True, upload_to='images/'),
        ),
    ]
