# Generated by Django 4.1.2 on 2022-10-29 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_remove_message_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.subject'),
        ),
    ]
